name: routed-fusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - easydict=1.9=py_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - griddataformats=0.5.0=py_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=nompi_py37h513d04c_102
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.10=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - matplotlib=3.2.0=1
  - matplotlib-base=3.2.0=py37h250f245_1
  - mkl=2020.1=219
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.10.0=hc9558a2_0
  - nspr=4.26=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py37h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.1.2=py37h718be6c_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - python=3.7.6=h357f687_4_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - scipy=1.5.0=py37ha3d9a3c_0
  - setuptools=47.3.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h8f50634_1
  - wheel=0.34.2=py_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h516909a_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.9.0
    - apptools==4.5.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - configobj==5.0.6
    - connected-components-3d==1.7.0
    - cython==0.29.20
    - decorator==4.4.2
    - envisage==4.9.2
    - freetype-py==2.1.0.post1
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.30.0
    - idna==2.10
    - imageio==2.8.0
    - importlib-metadata==1.7.0
    - markdown==3.2.2
    - mayavi==4.7.1
    - networkx==2.4
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - pandas==1.0.1
    - pip==20.1.1
    - plyfile==0.7.1
    - protobuf==3.12.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyface==6.1.2
    - pyglet==1.5.7
    - pygments==2.6.1
    - pymcubes==0.0.12
    - pyntcloud==0.1.2
    - pyopengl==3.1.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyquaternion==0.9.5
    - pyrender==0.1.43
    - pytz==2019.3
    - pywavefront==1.3.2
    - pywavelets==1.1.1
    - pyyaml==5.3
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-image==0.16.2
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.0
    - tqdm==4.43.0
    - traits==6.0.0
    - traitsui==6.1.3
    - trimesh==3.7.4
    - urllib3==1.25.9
    - vtk==8.1.2
    - werkzeug==1.0.1
    - zipp==3.1.0
prefix: /home/weders/anaconda3/envs/routed-fusion

