SETTINGS:
  machine: leonhard
  gpu: True
  experiment_path: #path to your experiment
RESUME:
  resume: False
  model: None
MODEL:
  contraction: 64
  depth: 1
  n_input_channels: 1
  n_output_channels: 2
  normalization: False
  residual: True
LOSS:
  name: combined
  crop_fraction: 0.
  vmin: 0.
  vmax: 10.
  weight_scale: 10.
TRAINING:
  train_batch_size: 4
  train_shuffle: True
  val_batch_size: 4
  val_shuffle: False
  n_epochs: 1000
OPTIMIZATION:
  lr: 1.e-05
  rho: 0.95
  eps: 1.e-07
  momentum: 0.9
  weight_decay: 0.01
  accumulate: True
  accumulation_steps: 8
  alternate: False
  alternate_steps: 5
DATA:
  root_dir: /media/weders/HV620S/data/shape-net/processed
  dataset: ShapeNet
  input: noisy_depth_octnetfusion
  target: depth
  resx: 320
  resy: 480
  noise_scale: 0.01
  outlier_scale: 0.01
  outlier_fraction: 0.99
  grid_resolution: 128
  train_scene_list: lists/shapenet/routing//train.test.txt
  val_scene_list: lists/shapenet/routing/val.test.txt
  test_scene_list: lists/shapenet/routing/test.txt
